name: action1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: printenv
      - run: ls -ltr
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: muhzilla
          password: ${{ secrets.DOCKERPW }}
      - run: docker build . --tag ${{ secrets.REGISTRY }}/sample:$GITHUB_RUN_NUMBER
      - run: docker push ${{ secrets.REGISTRY }}/sample:$GITHUB_RUN_NUMBER
